name: update-map

on:
  schedule:
    - cron: "0 */7 * * *"  # Ejecutar cada 7 horas
  workflow_dispatch:  # Permitir ejecución manual desde GitHub

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Asegura que se descargue todo el historial para evitar conflictos

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python DrugPolicyMap.py

    - name: Pull latest changes from remote
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git stash  # Guarda cambios locales temporalmente
        git pull --rebase origin main  # Descarga los últimos cambios remotos
        git stash pop  # Restaura los cambios locales guardados

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update GeoJSON map"
        git push origin main
