name: Update GeoJSON Map

on:
  schedule:
    - cron: '0 */7 * * *'  # Actualiza cada 7 horas
  workflow_dispatch:  # Permite ejecuciones manuales

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser geopy

    - name: Run the script
      run: |
        python DrugPolicyMap.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add drug_policy_alerts.geojson
        git commit -m "Update GeoJSON map"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
